# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
    - init: make
      command: nvm i v14.5.0 && npm i prettier -g && npm i --legacy-peer-deps && npm audit fix
github:
    # https://www.gitpod.io/docs/prebuilds/#configure-prebuilds
    prebuilds:
        master: true # enable for the default branch (even if it's not named "master")
        branches: true
        pullRequests: true
        pullRequestsFromForks: true
        addCheck: true
        addComment: false
        addBadge: true
        addLabel: true
vscode:
    extensions:
        - dbaeumer.vscode-eslint@2.1.5:9Wg0Glx/TwD8ElFBg+FKcQ==
        - esbenp.prettier-vscode@5.0.0:qca7d0cHbKkrkb5rvNlpcg==
        - flowtype.flow-for-vscode@1.5.0:AwOT6wgHTF43loZQCAUMLA==
