language: node_js
dist: xenial
node_js:
    - '6'
    - '8'
    - '10'
    - '12'
    - '14'
    - '16'
script:
    - cd test/support/express3 && npm install
    - cd ../express4 && npm install
    - cd ../../..
    - npm test
