#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/../@mapbox/mapbox-gl-style-spec/bin/gl-style-format.js" "$@"
  ret=$?
else 
  node  "$basedir/../@mapbox/mapbox-gl-style-spec/bin/gl-style-format.js" "$@"
  ret=$?
fi
exit $ret
