name: Format code using Prettier
on: [pull_request]

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: Install Prettier
              run: npm install --global prettier
            - name: Check format
              run: npx prettier --check .
            - name: Format code
              if: failure()
              run: npx prettier --write .
            - name: Commit changed files
              if: failure()
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: 'Beautified code'
